name        : libav
version     : 11.4
release     : 1
source     :
    - http://libav.org/releases/libav-11.4.tar.xz : 0b7dabc2605f3a254ee410bb4b1a857945696aab495fe21b34c3b6544ff5d525
license     : GPL-2.0+
summary     : Libav is a complete, cross-platform solution to decode, encode, record, convert and stream audio and video.
builddeps   :
    - pkgconfig(theora)
    - pkgconfig(ogg)
    - pkgconfig(vorbis)
    - pkgconfig(speex)
description : |
    Libav is a friendly and community-driven effort to provide its users with a set of portable, functional and high-performance libraries for dealing with multimedia formats of all sorts.
setup      : |
    ./configure --prefix=/usr \
                --disable-static \
                --enable-shared \
                --enable-libtheora \
                --enable-libvorbis \
                --enable-libspeex \
                --enable-zlib
build      : |
    %make
install    : |
    %make_install
